### PR TITLE
add typings

### PR DESCRIPTION
**Pull request by adityapurwa**
Added typescript typings so typescript user can use this library with ease.

### CODE REVIEW

**Comment by davidfrtala** [comment]
Any update on this?

**Comment by adityapurwa** [comment]
@davidfrtala Just waiting for @Charca to confirm on this, I personally used TypeScript extensively and having typings would help me .

**Comment by davidfrtala** [comment]
@adityapurwa have you also updated the typings for most recent version?
There are also some issues from what I see. For instance in SendApi class declaration, most of the `send*` functions returns `void` which is wrong, because they call `sendRequest()` and returns a Promise.

**Comment by adityapurwa** [comment]
@davidfrtala Not yet, thanks for tellling me! Will update it when I have time.

**Comment by Charca** [comment]
Thanks for the PR @adityapurwa. This looks good to me, but I honestly don't have a lot of experience with TypeScript so I'm probably not the best person to comment on it.

But this doesn't conflict with anything, so if you give me a 👍 I'll merge this in.

**Pull request closed without merging**
